# Generated by Django 2.2.3 on 2019-07-19 04:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(choices=[('제목1', '제목1 레이블'), ('제목2', '제목2 레이블'), ('제목3', '제목3 레이블')], help_text='포스팅 제목을 입력해주세요 최대 100자 안으로', max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('lnglat', models.CharField(blank=True, help_text='경도, 위도 포멧으로 입력', max_length=50, validators=[blog.models.lnglat_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
